import os
import subprocess
from datetime import datetime

BLOCKED_TOP_DIRS = {
    ".git",
    "runtime_experimental",
    "core",
    "app",
    "runtime",
}

SAFE_DIR_PREFIXES = (
    "examples/",
    "tests/",
    "environments/",
)

SAFE_FILE_PREFIXES = (
    "examples/",
    "tests/",
)

SAFE_EXTENSIONS = {".py"}


def run(cmd: str):
    result = subprocess.run(cmd, shell=True, capture_output=True, text=True)
    return result.stdout.strip(), result.stderr.strip(), result.returncode


def normalize_path(path: str) -> str:
    return str(path or "").replace("\\", "/").strip().strip("/")


def branch_name(task):
    ts = int(datetime.now().timestamp())
    return f"gitcube/mage_{task.get('id')}_{ts}"


def create_branch(name: str):
    return run(f"git checkout -b {name}")


def commit_all(message: str):
    safe_message = str(message).replace('"', "'")
    return run(f'git add . && git commit -m "{safe_message}"')


def push_branch(name: str):
    return run(f"git push origin {name}")


def create_pr(name: str, title: str):
    safe_title = str(title).replace('"', "'")
    return run(
        f'gh pr create --title "{safe_title}" --body "Auto-generated by GitCube MAGE v2" --base main'
    )


def cleanup_branch_to_main():
    run("git checkout main")


def validate_python_file(path: str):
    out, err, code = run(f'python -m py_compile "{path}"')
    if code != 0:
        return False, f"validation_failed:{err or out}"
    return True, "validation_ok"


def should_run_mage(task):
    title = str(task.get("title", "")).lower()
    payload = task.get("payload", {}) or {}
    problem = str(payload.get("problem", "")).lower()

    triggers = {
        "missing_init",
        "missing_init_group",
        "python_without_docs",
    }

    if problem in triggers:
        return True

    if "package structure" in title:
        return True

    if "project documentation" in title:
        return True

    return False


def extract_target_dirs(task):
    payload = task.get("payload", {}) or {}

    dirs = []

    path = normalize_path(payload.get("path"))
    if path:
        dirs.append(path)

    paths = payload.get("paths")
    if isinstance(paths, list):
        for p in paths:
            p = normalize_path(p)
            if p:
                dirs.append(p)

    unique = []
    seen = set()
    for d in dirs:
        if d not in seen:
            seen.add(d)
            unique.append(d)

    return unique


def top_dir(path: str) -> str:
    path = normalize_path(path)
    if not path:
        return ""
    return path.split("/", 1)[0]


def is_safe_directory(path: str):
    path = normalize_path(path)

    if not path:
        return False, "missing_path"

    if path == ".":
        return False, "root_not_supported"

    top = top_dir(path)
    if top in BLOCKED_TOP_DIRS:
        return False, f"blocked_dir:{top}"

    if not path.startswith(SAFE_DIR_PREFIXES):
        return False, "outside_safe_prefix"

    if not os.path.isdir(path):
        return False, "path_not_found"

    return True, "safe"


def is_safe_file(path: str):
    path = normalize_path(path)

    if not path:
        return False, "missing_path"

    top = top_dir(path)
    if top in BLOCKED_TOP_DIRS:
        return False, f"blocked_dir:{top}"

    if not path.startswith(SAFE_FILE_PREFIXES):
        return False, "outside_safe_prefix"

    _, ext = os.path.splitext(path)
    if ext not in SAFE_EXTENSIONS:
        return False, f"unsupported_extension:{ext}"

    if not os.path.isfile(path):
        return False, "path_not_found"

    return True, "safe"


def ensure_init_file(target_dir: str):
    init_path = os.path.join(target_dir, "__init__.py").replace("\\", "/")

    if os.path.exists(init_path):
        return False, "no_changes", init_path

    with open(init_path, "w", encoding="utf-8") as f:
        f.write('"""Package marker added by GitCube MAGE."""\n')

    return True, "created_init", init_path


def file_is_lightweight_for_docstring(path: str):
    try:
        with open(path, "r", encoding="utf-8") as f:
            content = f.read()
    except Exception:
        return False

    stripped = content.strip()
    if not stripped:
        return True

    lines = [x.strip() for x in content.splitlines() if x.strip()]

    if len(lines) <= 3 and all(not x.startswith(("def ", "class ", '"""', "import ", "from ")) for x in lines):
        return True

    return False


def ensure_module_docstring(path: str):
    try:
        with open(path, "r", encoding="utf-8") as f:
            content = f.read()
    except Exception as e:
        return False, f"read_failed:{e}", path

    stripped = content.lstrip()
    if stripped.startswith('"""') or stripped.startswith("'''"):
        return False, "no_changes", path

    if not file_is_lightweight_for_docstring(path):
        return False, "no_changes", path

    new_content = '"""Module bootstrap added by GitCube MAGE."""\n'
    if content.strip():
        new_content += "\n" + content
    else:
        new_content += "\n"

    with open(path, "w", encoding="utf-8") as f:
        f.write(new_content)

    return True, "created_docstring", path


def collect_candidate_python_files(base_dirs):
    candidates = []

    for base_dir in base_dirs:
        base_dir = normalize_path(base_dir)
        if not base_dir or not os.path.isdir(base_dir):
            continue

        for root, _, files in os.walk(base_dir):
            root = root.replace("\\", "/")
            for name in files:
                if not name.endswith(".py"):
                    continue
                full_path = os.path.join(root, name).replace("\\", "/")
                if full_path.endswith("/__init__.py"):
                    continue
                candidates.append(full_path)

    unique = []
    seen = set()
    for c in candidates:
        if c not in seen:
            seen.add(c)
            unique.append(c)

    return unique


def apply_missing_init_group(task):
    changed_files = []

    target_dirs = extract_target_dirs(task)
    if not target_dirs:
        return False, "missing_path", changed_files

    for target_dir in target_dirs:
        safe_ok, safe_reason = is_safe_directory(target_dir)
        if not safe_ok:
            continue

        changed, action_reason, file_path = ensure_init_file(target_dir)
        if changed:
            changed_files.append(file_path)

    if changed_files:
        return True, f"changed:{len(changed_files)}", changed_files

    return False, "no_changes", changed_files


def apply_python_without_docs(task):
    payload = task.get("payload", {}) or {}

    base_dirs = ["examples", "tests"]
    changed_files = []

    candidates = collect_candidate_python_files(base_dirs)

    for path in candidates[:20]:
        safe_ok, safe_reason = is_safe_file(path)
        if not safe_ok:
            continue

        changed, action_reason, file_path = ensure_module_docstring(path)
        if changed:
            changed_files.append(file_path)

    if changed_files:
        return True, f"changed:{len(changed_files)}", changed_files

    return False, "no_changes", changed_files


def apply_mage_changes(task):
    payload = task.get("payload", {}) or {}
    problem = str(payload.get("problem", "")).lower()
    title = str(task.get("title", "")).lower()

    if problem in {"missing_init", "missing_init_group"} or "package structure" in title:
        return apply_missing_init_group(task)

    if problem == "python_without_docs" or "project documentation" in title:
        return apply_python_without_docs(task)

    return False, "not_supported_task", []


def validate_changed_files(paths):
    for path in paths:
        _, ext = os.path.splitext(path)
        if ext == ".py":
            ok, reason = validate_python_file(path)
            if not ok:
                return False, reason
    return True, "validation_ok"


def run_mage_task(task):
    if not should_run_mage(task):
        return False, "not_supported_task"

    name = branch_name(task)

    out, err, code = create_branch(name)
    if code != 0:
        return False, f"branch_create_failed:{err or out}"

    try:
        changed, action_reason, changed_files = apply_mage_changes(task)
    except Exception as e:
        cleanup_branch_to_main()
        return False, f"edit_failed:{e}"

    if not changed:
        cleanup_branch_to_main()
        return False, action_reason

    valid, validation_reason = validate_changed_files(changed_files)
    if not valid:
        cleanup_branch_to_main()
        return False, validation_reason

    out, err, code = commit_all(task.get("title", "GitCube MAGE PR"))
    if code != 0:
        cleanup_branch_to_main()
        return False, f"commit_failed:{err or out}"

    out, err, code = push_branch(name)
    if code != 0:
        cleanup_branch_to_main()
        return False, f"push_failed:{err or out}"

    out, err, code = create_pr(name, task.get("title", "GitCube MAGE PR"))
    if code != 0:
        cleanup_branch_to_main()
        return False, f"pr_create_failed:{err or out}"

    cleanup_branch_to_main()
    return True, f"files_changed:{len(changed_files)}"
