import os
import subprocess
from datetime import datetime

BLOCKED_PATHS = {
    ".git",
    "runtime_experimental",
    "core",
    "app",
    "runtime",
}

SAFE_PREFIXES = (
    "examples/",
    "tests/",
    "environments/",
)

SAFE_EXTENSIONS = {".py"}


def run(cmd: str):
    result = subprocess.run(cmd, shell=True, capture_output=True, text=True)
    return result.stdout.strip(), result.stderr.strip(), result.returncode


def normalize_path(path: str) -> str:
    return str(path or "").replace("\\", "/").strip().strip("/")


def branch_name(task):
    ts = int(datetime.now().timestamp())
    return f"gitcube/mage_{task.get('id')}_{ts}"


def create_branch(name: str):
    return run(f"git checkout -b {name}")


def commit_all(message: str):
    safe_message = str(message).replace('"', "'")
    return run(f'git add . && git commit -m "{safe_message}"')


def push_branch(name: str):
    return run(f"git push origin {name}")


def create_pr(name: str, title: str):
    safe_title = str(title).replace('"', "'")
    return run(
        f'gh pr create --title "{safe_title}" --body "Auto-generated by GitCube MAGE" --base main'
    )


def cleanup_branch_to_main():
    run("git checkout main")


def validate_python_file(path: str):
    out, err, code = run(f'python -m py_compile "{path}"')
    if code != 0:
        return False, f"validation_failed:{err or out}"
    return True, "validation_ok"


def should_run_mage(task):
    title = str(task.get("title", "")).lower()
    payload = task.get("payload", {}) or {}
    problem = str(payload.get("problem", "")).lower()

    if "package structure" in title:
        return True

    if "missing_init" in problem:
        return True

    if "missing_init_group" in problem:
        return True

    return False


def extract_target_dir(task):
    payload = task.get("payload", {}) or {}

    path = normalize_path(payload.get("path"))
    if path:
        return path

    paths = payload.get("paths")
    if isinstance(paths, list) and paths:
        for p in paths:
            p = normalize_path(p)
            if p and p != ".":
                return p

    return ""


def is_safe_directory(path: str):
    path = normalize_path(path)

    if not path:
        return False, "missing_path"

    if path == ".":
        return False, "root_not_supported"

    top = path.split("/", 1)[0]
    if top in BLOCKED_PATHS:
        return False, f"blocked_dir:{top}"

    if not path.startswith(SAFE_PREFIXES):
        return False, "outside_safe_prefix"

    if not os.path.isdir(path):
        return False, "path_not_found"

    return True, "safe"


def ensure_init_file(target_dir: str):
    init_path = os.path.join(target_dir, "__init__.py")
    init_path = init_path.replace("\\", "/")

    if os.path.exists(init_path):
        return False, "no_changes", init_path

    with open(init_path, "w", encoding="utf-8") as f:
        f.write('"""Package marker added by GitCube MAGE."""\n')

    return True, "created_init", init_path


def run_mage_task(task):
    if not should_run_mage(task):
        return False, "not_supported_task"

    target_dir = extract_target_dir(task)
    safe_ok, safe_reason = is_safe_directory(target_dir)
    if not safe_ok:
        return False, safe_reason

    name = branch_name(task)

    out, err, code = create_branch(name)
    if code != 0:
        return False, f"branch_create_failed:{err or out}"

    try:
        changed, action_reason, init_path = ensure_init_file(target_dir)
    except Exception as e:
        cleanup_branch_to_main()
        return False, f"edit_failed:{e}"

    if not changed:
        cleanup_branch_to_main()
        return False, action_reason

    valid, validation_reason = validate_python_file(init_path)
    if not valid:
        cleanup_branch_to_main()
        return False, validation_reason

    out, err, code = commit_all(task.get("title", "GitCube MAGE PR"))
    if code != 0:
        cleanup_branch_to_main()
        return False, f"commit_failed:{err or out}"

    out, err, code = push_branch(name)
    if code != 0:
        cleanup_branch_to_main()
        return False, f"push_failed:{err or out}"

    out, err, code = create_pr(name, task.get("title", "GitCube MAGE PR"))
    if code != 0:
        cleanup_branch_to_main()
        return False, f"pr_create_failed:{err or out}"

    cleanup_branch_to_main()
    return True, f"file_changed:{init_path}"
