import os
import subprocess
from datetime import datetime

SAFE_EXTENSIONS = {".py"}

SAFE_PREFIXES = ("examples/", "tests/")


def run(cmd: str):
    result = subprocess.run(cmd, shell=True, capture_output=True, text=True)
    return result.stdout.strip(), result.stderr.strip(), result.returncode


def branch_name(task):
    ts = int(datetime.now().timestamp())
    return f"gitcube/{task.get('id')}_{ts}"


def create_branch(name: str):
    return run(f"git checkout -b {name}")


def commit_all(message: str):
    safe_message = str(message).replace('"', "'")
    return run(f'git add . && git commit -m "{safe_message}"')


def push_branch(name: str):
    return run(f"git push origin {name}")


def create_pr(name: str, title: str):
    safe_title = str(title).replace('"', "'")
    return run(
        f'gh pr create --title "{safe_title}" --body "Auto-generated by GitCube" --base main'
    )


def normalize_path(path: str) -> str:
    return str(path or "").replace("\\", "/").strip()


def is_safe_target(path: str):
    path = normalize_path(path)

    if not path or not os.path.exists(path):
        return False, "invalid_path"

    if not path.endswith(".py"):
        return False, "not_python"

    if not path.startswith(SAFE_PREFIXES):
        return False, "unsafe_path"

    return True, "safe"


# 🔥 УНІВЕРСАЛЬНИЙ FIX ENGINE
def apply_fixes(path: str):
    changed = False

    with open(path, "r", encoding="utf-8") as f:
        lines = f.readlines()

    new_lines = []

    for line in lines:
        stripped = line.strip()

        # ❌ remove debug prints
        if "print(" in stripped:
            changed = True
            continue

        # ❌ remove TODO
        if "TODO" in stripped or "todo" in stripped:
            changed = True
            continue

        # ❌ replace pass
        if stripped == "pass":
            new_lines.append("    raise NotImplementedError()\n")
            changed = True
            continue

        # ❌ fix bare except
        if stripped == "except:":
            new_lines.append("except Exception as e:\n")
            changed = True
            continue

        new_lines.append(line)

    if changed:
        with open(path, "w", encoding="utf-8") as f:
            f.writelines(new_lines)

    return changed


def run_pr_task(task):
    payload = task.get("payload", {}) or {}
    path = normalize_path(payload.get("path"))

    safe_ok, reason = is_safe_target(path)
    if not safe_ok:
        return False, reason

    name = branch_name(task)

    out, err, code = create_branch(name)
    if code != 0:
        return False, f"branch_fail:{err or out}"

    try:
        changed = apply_fixes(path)
    except Exception as e:
        run("git checkout main")
        return False, f"edit_fail:{e}"

    if not changed:
        run("git checkout main")
        return False, "no_changes"

    out, err, code = commit_all(task.get("title", "GitCube fix"))
    if code != 0:
        return False, f"commit_fail:{err or out}"

    out, err, code = push_branch(name)
    if code != 0:
        return False, f"push_fail:{err or out}"

    out, err, code = create_pr(name, task.get("title", "GitCube fix"))
    if code != 0:
        return False, f"pr_fail:{err or out}"

    return True, f"fixed:{path}"
