import os
import subprocess
from datetime import datetime

SAFE_EXTENSIONS = {".py"}

BLOCKED_FILES = {
    "actor_executor.py",
    "repo_analyzer.py",
    "run.sh",
    "run_loop.sh",
    "status.py",
    "v_bridge.py",
    "runtime_experimental/pr_actor.py",
    "runtime_experimental/os_sync.py",
    "runtime_experimental/object_store.py",
    "runtime_experimental/github_bridge.py",
}

SAFE_PREFIXES = (
    "examples/",
    "tests/",
)


def run(cmd: str):
    result = subprocess.run(cmd, shell=True, capture_output=True, text=True)
    return result.stdout.strip(), result.stderr.strip(), result.returncode


def branch_name(task):
    ts = int(datetime.now().timestamp())
    return f"gitcube/{task.get('id')}_{ts}"


def create_branch(name: str):
    return run(f"git checkout -b {name}")


def commit_all(message: str):
    safe_message = str(message).replace('"', "'")
    return run(f'git add . && git commit -m "{safe_message}"')


def push_branch(name: str):
    return run(f"git push origin {name}")


def create_pr(name: str, title: str):
    safe_title = str(title).replace('"', "'")
    return run(
        f'gh pr create --title "{safe_title}" --body "Auto-generated by GitCube" --base main'
    )


def normalize_path(path: str) -> str:
    return str(path or "").replace("\\", "/").strip()


def is_safe_target(path: str) -> tuple[bool, str]:
    path = normalize_path(path)

    if not path:
        return False, "missing_path"

    if not os.path.exists(path):
        return False, "path_not_found"

    _, ext = os.path.splitext(path)
    if ext not in SAFE_EXTENSIONS:
        return False, f"unsupported_extension:{ext}"

    if path in BLOCKED_FILES:
        return False, "blocked_file"

    if path.startswith("runtime_experimental/"):
        return False, "blocked_runtime_experimental"

    if path.startswith("core/") or path.startswith("runtime/") or path.startswith("app/"):
        return False, "blocked_core_runtime_app"

    if not path.startswith(SAFE_PREFIXES):
        return False, "outside_safe_prefix"

    return True, "safe"


def should_run_pr(task):
    title = str(task.get("title", "")).lower()
    return "debug prints" in title


def extract_target_path(task):
    payload = task.get("payload", {}) or {}
    path = payload.get("path")
    return normalize_path(path)


def force_remove_prints(path: str):
    changed = False

    with open(path, "r", encoding="utf-8") as f:
        lines = f.readlines()

    new_lines = []
    for line in lines:
        if "print(" in line:
            changed = True
            continue
        new_lines.append(line)

    if changed:
        with open(path, "w", encoding="utf-8") as f:
            f.writelines(new_lines)

    return changed


def run_pr_task(task):
    if not should_run_pr(task):
        return False, "not_supported_task"

    target_path = extract_target_path(task)
    safe_ok, safe_reason = is_safe_target(target_path)
    if not safe_ok:
        return False, safe_reason

    name = branch_name(task)

    out, err, code = create_branch(name)
    if code != 0:
        return False, f"branch_create_failed:{err or out}"

    try:
        changed = force_remove_prints(target_path)
    except Exception as e:
        run("git checkout main")
        return False, f"edit_failed:{e}"

    if not changed:
        run("git checkout main")
        return False, "no_changes"

    out, err, code = commit_all(task.get("title", "GitCube PR"))
    if code != 0:
        return False, f"commit_failed:{err or out}"

    out, err, code = push_branch(name)
    if code != 0:
        return False, f"push_failed:{err or out}"

    out, err, code = create_pr(name, task.get("title", "GitCube PR"))
    if code != 0:
        return False, f"pr_create_failed:{err or out}"

    return True, f"file_changed:{target_path}"
