import subprocess
import os
from datetime import datetime

SAFE_PATTERNS = [
    "print(",
]

def run(cmd):
    result = subprocess.run(cmd, shell=True, capture_output=True, text=True)
    return result.stdout.strip(), result.stderr.strip()

def branch_name(task):
    ts = int(datetime.now().timestamp())
    return f"gitcube/{task.get('id')}_{ts}"

def create_branch(name):
    run(f"git checkout -b {name}")

def commit_all(message):
    run("git add .")
    run(f'git commit -m "{message}"')

def push_branch(name):
    run(f"git push origin {name}")

def create_pr(name, title):
    run(f'gh pr create --title "{title}" --body "Auto-generated by GitCube" --base main')

def safe_remove_debug(path):
    changed = False

    with open(path, "r", encoding="utf-8") as f:
        lines = f.readlines()

    new_lines = []

    for line in lines:
        if any(p in line for p in SAFE_PATTERNS):
            changed = True
            continue
        new_lines.append(line)

    if changed:
        with open(path, "w", encoding="utf-8") as f:
            f.writelines(new_lines)

    return changed

def apply_debug_cleanup():
    touched = 0

    for root, _, files in os.walk("."):
        for f in files:
            if f.endswith(".py"):
                path = os.path.join(root, f)
                try:
                    if safe_remove_debug(path):
                        touched += 1
                except:
                    pass

    return touched

def should_run_pr(task):
    title = str(task.get("title", "")).lower()
    return "debug prints" in title

def run_pr_task(task):
    if not should_run_pr(task):
        return False, "not_supported_task"

    name = branch_name(task)

    create_branch(name)

    touched = apply_debug_cleanup()

    if touched == 0:
        return False, "no_changes"

    commit_all(task.get("title"))
    push_branch(name)
    create_pr(name, task.get("title"))

    return True, f"files_changed:{touched}"
